"""Add is_admin to User

Revision ID: 7c5f22946acc
Revises: 
Create Date: 2025-01-24 14:39:07.147624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c5f22946acc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_message')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    op.create_table('user_message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=10), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('emotion', sa.VARCHAR(length=50), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
